# fly.toml app configuration file generated for clowtracker on 2025-05-05T13:12:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clowtracker"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "443"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 443
  force_https = true
  min_machines_running = 1
  auto_stop_machines = false
  auto_start_machines = true
  processes = ["app"]
  pool_size = 1

[[mounts]]
  source = "clowtracker_data"
  destination = "/app/alert_states"

[processes]
  app = "gunicorn --bind 0.0.0.0:443 --timeout 120 --keep-alive 5 run_bot:app"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 443
  path = "/metrics"

[deploy]
  strategy = "rolling"
  max_unavailable = 0

[checks]
  [checks.health]
    port = 443
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "https"
